# 04 NumPy Exercises by Jose Portila

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### 1. Import NumPy as np

In [1]:
import numpy as np 

#### 2. Create an array of 10 zeros 

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [7]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

The reason you can't use np.fives(10) is that NumPy does not have a function named fives. This is because NumPy provides more general functions like np.full and np.ones, which can be used flexibly to create arrays filled with any value (not just 5).

Explanation
np.zeros Exists:

np.zeros(size) is a specific function because zero is commonly used as a default value in many numerical and computational applications.
Generalized Functions for Other Values:

Instead of creating specific functions like np.fives, np.tens, etc., NumPy provides general-purpose functions:
np.full(shape, value): For creating an array of any shape and value.
np.ones(size): For creating an array of ones, which can then be multiplied by a scalar (e.g., np.ones(10) * 5).
Consistency in API Design:

Having np.fives would require NumPy to create a separate function for every commonly used value (e.g., np.tens, np.hundreds), making the library less elegant and harder to maintain.
Instead, NumPy opts for a small set of versatile functions, such as np.full, which can generate arrays filled with any desired value.

#### 5. Create an array of the integers from 10 to 50

In [8]:
import numpy as np

# Create an array of integers from 10 to 50
np.arange(10, 51)



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Explanation
np.arange(start, stop):

start: The starting value of the array (inclusive).
stop: The ending value (exclusive). Since we want to include 50, we use 51 as the stop value.
Default Step:

If no step is provided, the default step size is 1, which generates a sequence of consecutive integers.

#### 6. Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 8. Create a 3x3 identity matrix

In [11]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

# Print the resulting matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 9. Use NumPy to generate a random number between 0 and 1

In [15]:

# Generate a random number between 0 and 1
random_number = np.random.rand()

# Print the random number
print(random_number)


0.4174993975614105


Explanation
np.random.rand():

Generates a random float between 0.0 and 1.0 from a uniform distribution.
No Arguments Required:

The function generates a single random number when no arguments are passed.


#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [14]:
# Generate an array of 25 random numbers from a standard normal distribution
random_numbers = np.random.randn(25)

# Print the resulting array
print(random_numbers)

[-2.31829567 -0.88610249  0.5479161  -0.43441216  0.2450654  -0.23199691
 -1.47794066 -0.85573618 -0.15562558 -0.09575216  1.52515474 -0.06687295
  0.61019314  0.62916715 -0.8119964   0.07098494 -0.68065546  0.64382654
 -0.66016622  1.05164706 -1.96786229 -0.91702916  0.90308918 -0.43303908
 -0.29280053]


Explanation
np.random.randn(N):

Generates N random numbers sampled from a standard normal distribution.
A standard normal distribution has a mean of 0 and a standard deviation of 1.
Shape of Output:

Since we specify 25, the output will be a 1D array with 25 elements.

#### 11. Create the following matrix:

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [2]:
import numpy as np

# Create the desired matrix
matrix = np.linspace(0.01, 1.0, 100).reshape(10, 10)

# Print the resulting matrix
print(matrix)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Explanation
np.linspace(start, stop, num):

Generates num evenly spaced values between start and stop.
In this case:
start = 0.01
stop = 1.0
num = 100 (10 rows × 10 columns).
reshape(10, 10):

Reshapes the 1D array of 100 values into a 10x10 2D matrix.

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [3]:
# Create an array of 20 linearly spaced points between 0 and 1
linear_points = np.linspace(0, 1, 20)

# Print the resulting array
print(linear_points)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code to produce the following output (from referrring to mat): 

``` 
array([[12, 13, 14, 15],  
       [17, 18, 19, 20],  
       [22, 23, 24, 25]])
```

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code below to produce the following output (from referring to mat): 
``` 20 ```

20

#### 15. Write code below to produce the following output (from referring to mat):
  
```
array([[ 2],
       [ 7],
       [12]])
```

array([[ 2],
       [ 7],
       [12]])

#### 16. Write code that produces the following output (from referring to mat)

``` array([21, 22, 23, 24, 25])```

array([21, 22, 23, 24, 25])

#### 17. Write code that produces the following output (from referring to mat)

```
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### 18. Get the sum of all the values in mat

325

#### 19. Get the standard deviation of the values in mat

7.2111025509279782

#### 20. Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])